# Generated by Django 3.0.4 on 2022-02-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sala', '0001_initial'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(blank=True, max_length=25, null=True)),
                ('credito', models.IntegerField(null=True)),
                ('locais', models.ManyToManyField(to='sala.Sala')),
                ('professores', models.ManyToManyField(to='professor.Professor')),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
                'db_table': 'Disciplina',
            },
        ),
    ]
