# Generated by Django 3.0.4 on 2022-02-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turma', '0001_initial'),
        ('disciplina', '0001_initial'),
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField(choices=[(1, 'Simples'), (2, 'Duplo'), (3, 'Terço'), (4, 'Quarto'), (5, 'Quinto'), (6, 'Sexto')])),
                ('dia', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira')])),
                ('horario', models.IntegerField(choices=[(1, '7:00 - 7:45'), (2, '7:45 - 8:30'), (3, '8:50 - 9:35'), (4, '9:35 - 10-20'), (5, '10:30 - 11:15'), (6, '11:15 - 12:00'), (7, '13:00 - 13:45'), (8, '13:45 - 14:30'), (9, '14:50 - 15:35'), (10, '15:35 - 16:20'), (11, '16:30 - 17:15'), (12, '17:15 - 18:00')])),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.Disciplina')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala.Sala')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.Turma')),
            ],
            options={
                'verbose_name_plural': 'Cards',
                'db_table': 'Card',
            },
        ),
    ]
